name: foresh_flutter
description: Foresh Flutter

# apk > flutter build apk —release --flavor dev -t lib/main/dev.dart, flutter build apk —release -t lib/main.dart
# 빌드 > flutter packages pub run build_runner build --delete-conflicting-outputs
# assets > fluttergen -c /Users/hyeokshin/StudioProjects/fortune/pubspec.yaml

publish_to: 'none'
# 1.0.0: 버전네임, 1: 버전코드
version: 1.0.0+1

# 3.0.0 이상을 지원하면서, 4.0.0미만에 버전도 작동하도록 함
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.12.0
  firebase_remote_config: ^4.2.0
  firebase_analytics: ^10.4.0
  firebase_crashlytics: ^3.3.0
  app_settings: ^4.2.0
  appmetrica_plugin: ^1.1.0
  package_info_plus: ^4.0.0

  # ui
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.6
  expansion_widget: ^0.0.3
  lottie: ^2.3.2
  material_dialogs: ^1.1.4
  page_view_indicators: ^2.0.0
  location: ^4.4.0
  image_picker: ^0.8.7+5
  image_cropper: ^3.0.3
  flutter_animation_progress_bar: ^2.3.1
  flutter_keyboard_visibility: ^5.4.1
  item_selector: ^0.2.0
  scroll_to_index: ^3.0.1
  awesome_dialog: ^3.0.2
  alt_sms_autofill: ^1.0.0
  pin_code_fields: ^7.4.0
  double_back_to_close: ^2.0.0
  avatar_glow: ^2.0.2
  delayed_display: ^2.0.0
  flutter_svg_provider: ^1.0.3
  add_to_cart_animation: ^2.0.3
  image: ^4.0.15
  scrollable_list_tab_scroller: ^1.1.0
  transparent_image: ^2.0.1
  flutter_styled_toast: ^2.1.3
  confetti: ^0.7.0
  percent_indicator: ^4.2.3
  skeletons: ^0.0.3
  flutter_bounceable: ^1.1.0
  sticky_headers: ^0.3.0+2
  animation_list: ^2.2.1

  # map
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  geolocator: ^9.0.2

  # state and dependency mgmt
  bloc_concurrency: ^0.2.1
  get_it: ^7.6.0
  flutter_bloc: ^8.1.2
  side_effect_bloc: ^1.0.0
  bloc_event_transformers: ^1.0.1
  bloc: ^8.1.1
  fluro: ^2.0.5

  # dart
  equatable: ^2.0.5
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  synchronized: ^3.1.0
  logger: ^1.3.0
  easy_localization: ^3.0.1

  # network
  http: ^0.13.6
  chopper: ^6.1.1
  jwt_decoder: 2.0.1
  stomp_dart_client: ^0.4.4

  # data
  single_item_storage: ^1.0.5
  single_item_secure_storage: ^0.1.0
  single_item_shared_prefs: ^0.0.4
  shared_preferences: ^2.1.1
  flutter_screenutil: ^5.7.0
  freezed_annotation: ^2.2.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner:
  flutter_native_splash: ^2.2.19

  flutter_lints: ^2.0.1
  # 패키지명변경: flutter pub run change_app_package_name:main com.new.package.name
  change_app_package_name: ^1.1.0
  # For testing.
  mockito: ^5.4.0
  # Code generator
  build_runner: ^2.4.3
  # Code generator from models (to json and from json)
  json_serializable: ^6.6.2
  # Freezed
  freezed: ^2.3.3
  # API code generator
  chopper_generator: ^6.0.0
  # Integration tests
  flutter_driver:
    sdk: flutter
  test: any
  # navigation testing
  bloc_test: ^9.1.1

flutter_native_splash:
  color: "#1b1c24"
  image: assets/images/splash/splash_default.png
  color_dark: "#1b1c24"
  image_dark: assets/images/splash/splash_default.png

  android_12:
    image: assets/images/splash/android12splash.png
    icon_background_color: "#1b1c24"
    image_dark: assets/images/splash/android12splash.png
    icon_background_color_dark: "#1b1c24"

  web: false

flutter_gen:
  output: lib/core/gen/
  lineLength: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  #  generate: false
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/translations/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
    - family: Pretendard-ExtraLight
      fonts:
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
    - family: Pretendard-Light
      fonts:
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
    - family: Pretendard-Regular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
    - family: Pretendard-Medium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
    - family: Pretendard-SemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
    - family: Pretendard-Bold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
    - family: Pretendard-ExtraBold
      fonts:
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
    - family: Pretendard-Black
      fonts:
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900