// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA80KcNjR7vxokbPJ2KV82t5jCrodsLBDM',
    appId: '1:756092673843:web:eb6c4ab0864a9882786846',
    messagingSenderId: '756092673843',
    projectId: 'fortune-938ea',
    authDomain: 'fortune-938ea.firebaseapp.com',
    storageBucket: 'fortune-938ea.appspot.com',
    measurementId: 'G-HMHGJYQ465',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMsyX3yngptd4A4mkiWrVV_in4DO07auo',
    appId: '1:756092673843:android:c56f0cdc7a24b618786846',
    messagingSenderId: '756092673843',
    projectId: 'fortune-938ea',
    storageBucket: 'fortune-938ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI9KdFJi33ynkCELOPP_njjDJFcRYvNo8',
    appId: '1:756092673843:ios:6b13164f546879d1786846',
    messagingSenderId: '756092673843',
    projectId: 'fortune-938ea',
    storageBucket: 'fortune-938ea.appspot.com',
    iosClientId: '756092673843-aobbdelvomu1or34mmq429aqrnoko9pf.apps.googleusercontent.com',
    iosBundleId: 'com.foresh.fortune',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI9KdFJi33ynkCELOPP_njjDJFcRYvNo8',
    appId: '1:756092673843:ios:0bbd2a214044d44b786846',
    messagingSenderId: '756092673843',
    projectId: 'fortune-938ea',
    storageBucket: 'fortune-938ea.appspot.com',
    iosClientId: '756092673843-qidkcek8jt583cgv3jrct0j1ulcel85b.apps.googleusercontent.com',
    iosBundleId: 'com.foresh.fortune.RunnerTests',
  );
}
