// import 'package:foresh_flutter/domain/entities/main_entity.dart';
//
// List<MainHistoryEntity> historySampleList = [
//   MainHistoryEntity(
//       latitude: 0,
//       longitude: 0,
//       grade: 0,
//       userId: 3,
//       nickname: '닉네임1',
//       markerId: 123,
//       id: 123,
//       createdAt: '',
//       modifiedAt: ''),
//   MainHistoryEntity(
//       latitude: 0,
//       longitude: 0,
//       grade: 0,
//       userId: 3,
//       nickname: '닉네임2',
//       markerId: 123,
//       id: 123,
//       createdAt: '',
//       modifiedAt: ''),
//   MainHistoryEntity(
//       latitude: 0,
//       longitude: 0,
//       grade: 0,
//       userId: 3,
//       nickname: '닉네임3',
//       markerId: 123,
//       id: 123,
//       createdAt: '',
//       modifiedAt: ''),
//   MainHistoryEntity(
//       latitude: 0,
//       longitude: 0,
//       grade: 0,
//       userId: 3,
//       nickname: '닉네임4',
//       markerId: 123,
//       id: 123,
//       createdAt: '',
//       modifiedAt: ''),
//   MainHistoryEntity(
//       latitude: 0,
//       longitude: 0,
//       grade: 0,
//       userId: 3,
//       nickname: '닉네임5',
//       markerId: 123,
//       id: 123,
//       createdAt: '',
//       modifiedAt: ''),
//   MainHistoryEntity(
//       latitude: 0,
//       longitude: 0,
//       grade: 0,
//       userId: 3,
//       nickname: '닉네임2',
//       markerId: 123,
//       id: 123,
//       createdAt: '',
//       modifiedAt: ''),
//   MainHistoryEntity(
//       latitude: 0,
//       longitude: 0,
//       grade: 0,
//       userId: 3,
//       nickname: '닉네임1',
//       markerId: 123,
//       id: 123,
//       createdAt: '',
//       modifiedAt: ''),
//   MainHistoryEntity(
//       latitude: 0,
//       longitude: 0,
//       grade: 0,
//       userId: 3,
//       nickname: '닉네임2',
//       markerId: 123,
//       id: 123,
//       createdAt: '',
//       modifiedAt: ''),
//   MainHistoryEntity(
//       latitude: 0,
//       longitude: 0,
//       grade: 0,
//       userId: 3,
//       nickname: '닉네임1',
//       markerId: 123,
//       id: 123,
//       createdAt: '',
//       modifiedAt: ''),
//   MainHistoryEntity(
//       latitude: 0,
//       longitude: 0,
//       grade: 0,
//       userId: 3,
//       nickname: '닉네임2',
//       markerId: 123,
//       id: 123,
//       createdAt: '',
//       modifiedAt: ''),
//   MainHistoryEntity(
//       latitude: 0,
//       longitude: 0,
//       grade: 0,
//       userId: 3,
//       nickname: '닉네임1',
//       markerId: 123,
//       id: 123,
//       createdAt: '',
//       modifiedAt: ''),
//   MainHistoryEntity(
//       latitude: 0,
//       longitude: 0,
//       grade: 0,
//       userId: 3,
//       nickname: '닉네임2',
//       markerId: 123,
//       id: 123,
//       createdAt: '',
//       modifiedAt: ''),
//   MainHistoryEntity(
//       latitude: 0,
//       longitude: 0,
//       grade: 0,
//       userId: 3,
//       nickname: '닉네임1',
//       markerId: 123,
//       id: 123,
//       createdAt: '',
//       modifiedAt: ''),
//   MainHistoryEntity(
//       latitude: 0,
//       longitude: 0,
//       grade: 0,
//       userId: 3,
//       nickname: '닉네임2',
//       markerId: 123,
//       id: 123,
//       createdAt: '',
//       modifiedAt: ''),
//   MainHistoryEntity(
//       latitude: 0,
//       longitude: 0,
//       grade: 0,
//       userId: 3,
//       nickname: '닉네임1',
//       markerId: 123,
//       id: 123,
//       createdAt: '',
//       modifiedAt: ''),
//   MainHistoryEntity(
//       latitude: 0,
//       longitude: 0,
//       grade: 0,
//       userId: 3,
//       nickname: '닉네임2',
//       markerId: 123,
//       id: 123,
//       createdAt: '',
//       modifiedAt: ''),
//   MainHistoryEntity(
//       latitude: 0,
//       longitude: 0,
//       grade: 0,
//       userId: 3,
//       nickname: '닉네임1',
//       markerId: 123,
//       id: 123,
//       createdAt: '',
//       modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임2',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임1',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임2',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임1',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임2',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임1',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임2',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임1',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임2',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임1',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임2',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임1',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임2',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임1',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임2',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임1',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임2',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임1',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임2',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임1',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임2',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임1',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임2',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임1',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임2',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임1',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임2',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임1',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임2',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임1',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
//   // MainHistoryEntity(
//   //     latitude: 0,
//   //     longitude: 0,
//   //     grade: 0,
//   //     userId: 3,
//   //     nickname: '닉네임2',
//   //     markerId: 123,
//   //     id: 123,
//   //     createdAt: '',
//   //     modifiedAt: ''),
// ];
