create table "public"."app_update" (
    "id" bigint generated by default as identity not null,
    "title" text default ''::text,
    "content" text default ''::text,
    "created_at" timestamp with time zone not null default now(),
    "is_active" boolean default false
);


alter table "public"."app_update" enable row level security;

alter table "public"."markers" alter column "latitude" set data type numeric using "latitude"::numeric;

alter table "public"."markers" alter column "longitude" set data type numeric using "longitude"::numeric;

CREATE UNIQUE INDEX app_update_pkey ON public.app_update USING btree (id);

alter table "public"."app_update" add constraint "app_update_pkey" PRIMARY KEY using index "app_update_pkey";

create policy "Enable read access for all users"
on "public"."app_update"
as permissive
for select
to public
using (true);



