alter table "public"."personal_info" drop constraint "personal_info_pkey";

drop index if exists "public"."personal_info_pkey";

drop table "public"."personal_info";

create table "public"."privacy_policy" (
    "id" bigint generated by default as identity not null,
    "kr_title" text,
    "kr_content" text,
    "en_title" text not null default ''::text,
    "en_content" text not null default ''::text,
    "created_at" timestamp with time zone default now()
);


alter table "public"."privacy_policy" enable row level security;

CREATE UNIQUE INDEX personal_info_pkey ON public.privacy_policy USING btree (id);

alter table "public"."privacy_policy" add constraint "personal_info_pkey" PRIMARY KEY using index "personal_info_pkey";

create policy "Enable read access for all users"
on "public"."privacy_policy"
as permissive
for select
to public
using (true);



