create table "public"."country_info" (
    "id" bigint generated by default as identity not null,
    "en_name" text not null,
    "iso2" text not null,
    "iso3" text,
    "phone_code" integer,
    "kr_name" text
);


alter table "public"."country_info" enable row level security;

alter table "public"."users" add column "country_info" bigint;

CREATE UNIQUE INDEX country_code_pkey ON public.country_info USING btree (id);

alter table "public"."country_info" add constraint "country_code_pkey" PRIMARY KEY using index "country_code_pkey";

alter table "public"."users" add constraint "users_country_info_fkey" FOREIGN KEY (country_info) REFERENCES country_info(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."users" validate constraint "users_country_info_fkey";

create policy "Enable read access for all users"
on "public"."country_info"
as permissive
for select
to anon
using (true);



