name: iOS Build and Sign

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_P12_CERTIFICATE }}
          p12-password: ${{ secrets.APPLE_P12_PASSWORD }}

      - name: Install the provisioning profile
        env:
          PROVISIONING_CERTIFICATE_BASE64: ${{ secrets.APPLE_PROVISIONING_PROFILE }}
        run: |
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          echo -n "$PROVISIONING_CERTIFICATE_BASE64" | base64 --decode --output $PP_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles     

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Install Flutter Dependencies
        run: flutter pub get

      - run: dart pub global activate flutter_gen
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Build Flutter for iOS
        run: flutter build ios --release --no-codesign

      - name: Build resolve Swift dependencies
        run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release

      # DEVELOPMENT_TEAM: 팀 아이디(Xcode 혹 검색해보면나옴) ex) "DEVELOPMENT_TEAM[sdk=iphoneos*]" = HQ5SJU4229;
      # CODE_SIGN_IDENTITY: 키체인에서 확인.
      # PROVISIONING_PROFILE: cat xxxx.mobileprovision | grep -A 1 -a UUID | grep "string" | sed -E "s/.*>([^<]*)<.*/\1/g"
      - name: Build xArchive
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -sdk 'iphoneos' \
                     -destination 'generic/platform=iOS' \
                     -archivePath build-output/app.xcarchive \
                     DEVELOPMENT_TEAM="HQ5SJU4229" \
                     PROVISIONING_PROFILE="42a506b7-8ee3-43c7-8543-17abf59826b0" \
                     clean archive \
                     CODE_SIGN_IDENTITY="iPhone Distribution: HyeokShin Kwon (HQ5SJU4229)" 

      - name: Export ipa
        run: xcodebuild -exportArchive -archivePath build-output/app.xcarchive -exportPath build-output/ios -exportOptionsPlist ios/ExportOptions.plist

      - name: Publish iOS Artefacts
        uses: actions/upload-artifact@v1
        with:
          name: release-ios
          path: build-output/ios