name: iOS Build and Sign

on:
  push:
    branches:
      - feature/myinventory

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Decode Certificate
        run: echo "${{ secrets.APPLE_P12_CERTIFICATE }}" | base64 --decode > cert.p12

      - name: Decode Provisioning Profile
        run: echo "${{ secrets.APPLE_PROVISIONING_PROFILE }}" | base64 --decode > profile.mobileprovision

      - name: Install Certificate and Provisioning Profile
        run: |
          security create-keychain -p password build.keychain
          security default-keychain -s build.keychain
          security import cert.p12 -k build.keychain -P ${{ secrets.APPLE_P12_PASSWORD }} -T /usr/bin/codesign
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles/
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build and Sign
        run: |
          xcodebuild -workspace Runner.xcworkspace \
                     -scheme Runner \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $PWD/build/YourApp.xcarchive \
                     archive \
                     CODE_SIGN_IDENTITY="iPhone Distribution" \
                     PROVISIONING_PROFILE_SPECIFIER="fortune_product"