name: Supabase Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PRODUCTION_PROJECT_ID }}

    steps:
      # 저장소의 코드를 체크아웃.
      - name: 브랜치 체크아웃
        uses: actions/checkout@v3

      # Supabase CLI를 설정합니다.
      - name: Supabase CLI 설정
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # Supabase 프로젝트를 연결합니다.
      - name: Supabase 프로젝트 연결
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      # 데이터베이스의 변경 사항을 푸시합니다.
      - name: 데이터베이스 푸시
        run: supabase db push